---
#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

title: Kathy Truong | Software Engineer
logo: # You can add own logo
description: Software Engineer Personal Blog
copyright: Copyright 2022 by @kathytruong
# Preloader
preloader: true # To disable preloader change value to false

menu:
  - name: Home
    url: /
  - name: ReadMe
    url: /about/
  - name: Fun Projects
    url: /projects/
  - name: Contact
    url: /contact/

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

layout_home_page: false # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: I am a software engineer at heart with a love for hands on creativity and a particular eye for design. I've been building all sorts of websites since 10 years old, where I spent time stealing other people's HTML code and learning how to build my own profile on Neopets. Since then, I've been hooked on code.
  hero-banner: /assets/images/Katsirius.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Kathy Truong

#-------------------------------
# Contact Info
contact:
  email: kathy.yvy.truong@gmail.com
  phone: 1-737-471-2605
  address:
    city: Austin

# Contact Form
contact-form: example@email.com

# Social links
social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-twitter-alt", link: "#" }
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/kathy-truong-25bb7955/" }
  - { icon: "ti-github", link: "#" }

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
